const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()
p.user.findMany({ select: { email: true, role: true } })
    .then(users => users.forEach(u => console.log(u.email, '->', u.role)))
    .finally(() => p.$disconnect())
